import { defineConfig } from 'cspell'

export default defineConfig({
  words: [
    'aabbggrr',
    'asakusa',
    'azat',
    "bahá'í",
    'changelogen',
    'changelogithub',
    'fushimi',
    'geocodes',
    'humanwhocodes',
    'inari',
    'kitesurfing',
    'nakameguro',
    'narita',
    'nishiki',
    'onibus',
    'placemark',
    'placemarks',
    'pinbook',
    'senso',
    'shinjuku',
    'tidepool',
    'trailhead',
    'wingsuit',
  ],
  ignorePaths: [
    'example',
    '.github',
    'changelog.md',
    'license',
    'pnpm-lock.yaml',
    'tsconfig.json',
  ],
  dictionaries: ['css', 'html', 'node', 'npm', 'typescript'],
  useGitignore: true,
  language: 'en',
})
